global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

storage:
  tsdb:
    out_of_order_time_window: 30m

otlp:
  promote_resource_attributes:
    - service.name
    - service.version
    - deployment.environment.name
    - service.group
    - vcs.revision

scrape_configs: []
