declare namespace NodeJS {
  interface ProcessEnv {
    DATABASE_URL: string;
    RESEND_API_KEY: string;
    RESEND_API_BASE_URL?: string;
    RESEND_WEBHOOK_SECRET: string;
    RESEND_REPLY_TO: string;
    EMAIL_v2_API_KEY?: string;
    EMAIL_V2_API_KEY?: string;
    OUTBOX_DRAIN_API_KEY: string;
    CONVERSATION_EVENTS_SINKS?: string;
    CONVERSATION_EVENTS_NATS_SERVERS?: string;
    CONVERSATION_EVENTS_NATS_STREAM?: string;
    CONVERSATION_EVENTS_NATS_SUBJECT?: string;
    CONVERSATION_EVENTS_NATS_TOKEN?: string;
    CONVERSATION_EVENTS_NATS_USERNAME?: string;
    CONVERSATION_EVENTS_NATS_PASSWORD?: string;
    CONVERSATION_EVENTS_NATS_TLS_MODE?: string;
    CONVERSATION_EVENTS_NATS_TLS_CA_PEM?: string;
    CONVERSATION_EVENTS_NATS_TLS_CERT_PEM?: string;
    CONVERSATION_EVENTS_NATS_TLS_KEY_PEM?: string;
    CONVERSATION_EVENTS_KAFKA_BROKERS?: string;
    CONVERSATION_EVENTS_KAFKA_CLIENT_ID?: string;
    CONVERSATION_EVENTS_KAFKA_TOPIC?: string;
    CONVERSATION_EVENTS_KAFKA_SECURITY_PROTOCOL?: string;
    CONVERSATION_EVENTS_KAFKA_SASL_MECHANISM?: string;
    CONVERSATION_EVENTS_KAFKA_SASL_USERNAME?: string;
    CONVERSATION_EVENTS_KAFKA_SASL_PASSWORD?: string;
    CONVERSATION_EVENTS_KAFKA_TLS_CA_PEM?: string;
    CONVERSATION_EVENTS_KAFKA_TLS_CERT_PEM?: string;
    CONVERSATION_EVENTS_KAFKA_TLS_KEY_PEM?: string;
  }
}
